<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Calculate Commission</name>
   <tag></tag>
   <elementGuidId>ad2acc5b-06d5-4bd1-8094-df68559be937</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirmAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ecb13a6d-b538-4f11-a9d7-a7dee0a6c490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1490bec-870a-4c9f-968b-80ba765f91d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmAmount</value>
      <webElementGuid>e4f1cccd-3c05-4a4a-aa1e-937acfbfb959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btn-sm text-dark px-0 text-decoration-none</value>
      <webElementGuid>2547e22e-af18-49e1-9e18-5210e7d8c6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Calculate Commission</value>
      <webElementGuid>4a1e0d07-9bb9-4b6a-88e0-f0d8ca324104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmAmount&quot;)</value>
      <webElementGuid>42f39bbf-848a-4cb5-a9ca-99540bbdd643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='confirmAmount']</value>
      <webElementGuid>fcd9057f-0db3-4efa-91c2-8918662e2ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>82ce5a1a-4d07-4a6d-a2fe-95ea562f6db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INR'])[1]/following::button[1]</value>
      <webElementGuid>02c9e33c-aca1-479c-beb9-1015e8c9c506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deal Amount :'])[1]/following::button[1]</value>
      <webElementGuid>6a89245e-a1a4-4d96-bc09-fc910b4f9c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calculate Commission']/parent::*</value>
      <webElementGuid>2e2a955a-d6aa-44e8-8ebd-0b781f7bf712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/button</value>
      <webElementGuid>0e28d8bb-fb03-4e7f-9ff7-8feceb9225fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'confirmAmount' and (text() = ' Calculate Commission' or . = ' Calculate Commission')]</value>
      <webElementGuid>89f68c44-65b8-43d6-877e-cbdff10380c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
