<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Charges )_charge_bear</name>
   <tag></tag>
   <elementGuidId>94424f71-3a43-4017-a5a5-348471eb448a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='charge_bear1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#charge_bear1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf53c249-f1f2-4249-ba10-e680e78dd8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>85a638f9-fbaa-4a0e-94e0-18770b7f15dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>charge_bear</value>
      <webElementGuid>9be73b9b-9670-4d3c-ba94-b4b60f4777a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>869152e1-dc87-4af1-b3d7-ec46142e3ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>charge_bear1</value>
      <webElementGuid>d832e3e7-6d42-40b6-ba03-f4b8dae45a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>invitor</value>
      <webElementGuid>80e7e139-863f-4ef4-a70d-1190f4f48228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;charge_bear1&quot;)</value>
      <webElementGuid>5064976f-9364-4768-b154-093b1ee2ee0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='charge_bear1']</value>
      <webElementGuid>bcdd4cf4-2567-4f57-b9ac-f9b33546919d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>c5b2e63c-5f89-4338-9154-5cbeda4c4d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>a35d3033-b6e2-40a7-8561-c449829e5dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'charge_bear' and @type = 'radio' and @id = 'charge_bear1']</value>
      <webElementGuid>18b777c3-9522-4d3e-9fef-fa6f9686336f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
